module DigYukko
  module MapObjectTableManager
    def self.fetch(score)
      LEVEL_TO_ADDITIONAL_TABLE[LevelManager.calc_level(score)]
    end

    LEVEL_TO_ADDITIONAL_TABLE = {
      1 => {},
      2 => {
        WideSpreadBomb1 => 4,
      },
      3 => {
        WideSpreadBomb1 => 8,
      },
      4 => {
        ProjectileCostumeItem => 1,
        WideSpreadBomb1 => 8,
        WideSpreadBomb2 => 1,
      },
      5 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 1,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 2,
      },
      6 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 1,
        WideSpreadBomb1 => 8,
        WideSpreadBomb2 => 2,
      },
      7 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 2,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 2,
        HorizontalBomb1 => 2,
      },
      8 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 2,
        WideSpreadBomb1 => 8,
        WideSpreadBomb2 => 2,
        HorizontalBomb1 => 2,
      },
      9 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 2,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 2,
        HorizontalBomb1 => 2,
        VerticalBomb1 => 2,
      },
      10 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 2,
        WideSpreadBomb1 => 8,
        WideSpreadBomb2 => 2,
        HorizontalBomb1 => 2,
        VerticalBomb1 => 2,
      },
      11 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 4,
        HorizontalBomb1 => 2,
        VerticalBomb1 => 2,
      },
      12 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 2,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        VerticalBomb1 => 2,
      },
      13 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 4,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        VerticalBomb1 => 2,
      },
      14 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 2,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        VerticalBomb1 => 2,
        VerticalBomb2 => 2,
      },
      15 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 4,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        VerticalBomb1 => 2,
        VerticalBomb2 => 2,
      },
      16 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 2,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        HorizontalBomb3 => 2,
        VerticalBomb1 => 2,
        VerticalBomb2 => 2,
      },
      17 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 4,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        HorizontalBomb3 => 2,
        VerticalBomb1 => 2,
        VerticalBomb2 => 2,
      },
      18 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 2,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        HorizontalBomb3 => 2,
        VerticalBomb1 => 2,
        VerticalBomb2 => 2,
        VerticalBomb3 => 2,
      },
      19 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 4,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        HorizontalBomb3 => 2,
        VerticalBomb1 => 2,
        VerticalBomb2 => 2,
        VerticalBomb3 => 2,
      },
      20 => {
        ProjectileCostumeItem => 1,
        HardBreakableBlock => 3,
        WideSpreadBomb1 => 6,
        WideSpreadBomb2 => 2,
        WideSpreadBomb3 => 2,
        HorizontalBomb1 => 2,
        HorizontalBomb2 => 2,
        HorizontalBomb3 => 2,
        VerticalBomb1 => 2,
        VerticalBomb2 => 2,
        VerticalBomb3 => 2,
      },
    }
  end
end
