---
:log:
  :level:      :debug
  :shift_age:  3
  :shift_size: 1048576
:window:
  :width:  768
  :height: 480
:font:
#  デフォルトフォントをカスタマイズする場合は
#  以下を設定する
#  :regular:
#    :size: 22
#    :name: 'FontName'
#    :path: data/fonts/font_file.ttf
